config/routes.rb
ApApp1::Application.routes.draw do
 
  root to: 'convos#index'

  resources :convos, :shallow => true do
    resources :docs
    resources :posts do
      resources :docs
    end
  end
    
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions=>'sessions'}
  resources :users, :only => [:show, :index, :update] do
    member do
      get :activity, :documents, :avatar#, :tracked, :trackers, 
    end
  end
  
  resources :subjects
  resources :topics
  resources :exams
  resources :colleges

  put 'upmerit_convo', to: 'convos#upmerit'
  put 'demerit_convo', to: 'convos#demerit'
  put 'upmerit_post', to: 'posts#upmerit'
  put 'demerit_post', to: 'posts#demerit'
 
  get "pages/home"
  get "pages/help"
  get "pages/about"
  get "pages/rules"

  

    
    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :merits, :umerits, :name, :colleges, :current_exams, :past_exams, :gradelevel, :school, :provider, :uid, :rank, :pic_url, :bday, :gpa, :avatar, :remote_avatar_url, :remove_avatar, :thumbnail, :admin
  
  mount_uploader :avatar, FileUploader
  # attr_accessible :title, :body

has_many :posts
has_many :convos
has_many :docs
has_many :relationships, foreign_key: 'tracker_id', dependent: :destroy
has_many :tracked_users, through: :relationships, source: :tracked

has_many :reverse_relationships, foreign_key: 'tracked_id', class_name: "Relationship", dependent: :destroy
has_many :trackers, through: :reverse_relationships, source: :tracker

 #Facebook oauth code

 def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
   user = User.where(:provider => auth.provider, :uid => auth.uid).first
   unless user
     user = User.create(name:auth.extra.raw_info.name,
                          provider:auth.provider,
                          uid:auth.uid,
                          email:auth.info.email,
                          password:Devise.friendly_token[0,20],
                          pic_url:auth.info.image,
                          bday:auth.info.user_birthday
                          )
   end
   user
 end

 def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
 end
 
# User merits and rank updating => called for new sessions

def login_merits
  #Currently uses Western time zone; set to get 25 points for logging in on your birthday along with notice HAPPY BIRTHDAY!!
  
  if self.last_sign_in_at.in_time_zone(-5).day != Time.now.in_time_zone(-5).day
    self.merits += 20
  end
end

def update_rank
  ranks = ["Tabula Rasa", "Pupil", "Scholar", "Sage", "Elder", "Illuminati", "G Whiz"]
  rank_level = [250, 500, 1000, 3000, 5000, 10000]
  
   if merits < rank_level[0]
    self.rank = ranks[0]
   elsif merits < rank_level[1]
    self.rank = ranks[1]
   elsif merits < rank_level[2]
    self.rank = ranks[2]
   elsif merits < rank_level[3]
    self.rank = ranks[3]
   elsif merits < rank_level[4]
    self.rank = ranks[4]
   elsif merits < rank_level[5]
    self.rank = ranks[5]
   else
    self.rank = ranks[6]
   end

end

def update_merits
  # Method run on login to calculate total merits for the user
  # THIS IS THE HEART OF THE MERIT SYSTEM; ABSOLUTELY DO NOT F*** WITH THIS!
  # Not the simplest implementation, but allows flexibility to easily integrate other sources of merits (e.g. direct granting of merits to users from others...)
  
  # Initializing two dummy variables:  
    convo_merits = 0
    post_merits = 0   
    
  # personal merits = merits earned through posting activity, not thumbs up
  # quality merits = the merits a user has derived from their posts and conversations
  # umerits = quality merits as of a user's last login
    personal_merits = self.merits - self.umerits
    
  # calculating all the "quality merits" a user has ever earned from posting
    self.convos.each{|convo| convo_merits += convo.merits}
    self.posts.each{|post| post_merits += post.merits}
    quality_merits = (convo_merits + post_merits)/2
    
  #we'll save this as "umerits", so we can keep track for the next iteration
    self.umerits = quality_merits
  # And finally, a user's total merits
    self.merits = personal_merits + quality_merits
    self.save    
end

#User tracking code #=> This is used for "tracking" code that would assist implementation of a friend/follow system for users

def tracking?(other_user)
  relationships.find_by_tracked_id(other_user.id)
end

def track!(other_user)
  relationships.create!(tracked_id: other_user.id)
end

def untrack!(other_user)
  relationship.find_by_tracked_id(other_user.id).destroy
end

def feed
  Post.from_users_tracked_by(self)
end

def self.from_users_tracked_by(user)
  tracked_user_ids = "SELECT tracked_id FROM relationships WHERE tracker_id = :user_id"
  where("user_id IN (#{tracked_user_ids}) OR user_id = :user_id", user_id: user.id)
end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    #raise request.env["omniauth.auth"].to_yaml #=> to see error with generated hash
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      #@user.login_merits
      @user.update_merits
      @user.update_rank
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
    
  end
  
  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    # Or alternatively,
    # raise ActionController::RoutingError.new('Not Found')
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end
  
  def activity
    @user = User.find_by_id(params[:id])
  end
  
  def documents
    @user = User.find_by_id(params[:id])
    @docs = @user.docs
    @convos = @user.convos
    @posts = @user.posts
  end
  
  def update
    @user = User.find_by_id(params[:id])
    @user.update_attributes(params[:user])
    redirect_to root_url
  end
  
  
  def tracked
    @title = "Tracked"
    @user = User.find(params[:id])
    @users = @user.tracked_users.page(params[:page]).per_page(20)
    render 'show_track'
  end
  
  def trackers
    @title = "Trackers"
    @user = User.find(params[:id])
    @users = @user.tracked_users.page(params[:page]).per_page(20)
    render 'show_track'
  end
  
  def avatar
    @user = User.find_by_id(params[:id])
  end
  
  # def upmerit
  #     @user = User.find(params[:id])
  #     if demerituser(current_user,1)
  #       @user.update_attribute :merits, @user.merits + 1
  #     end
  #     respond_to do |f|
  #       f.js
  #     end
  #   end
  #   
  #   def demerit
  #     @user = User.find(params[:id])
  #     if demerituser(current_user,2)
  #       @user.update_attribute :merits, @user.merits - 1
  #     end
  #     respond_to do |f|
  #       f.js
  #     end
  #   end
  
  # def tracking
  #   @title = "Following"
  #   @user = User.find(params[:id])
  #   @users = @user.followed_users
  #   render 'show_follow'
  # end
  # 
  # def trackers
  #   @title = "Followers"
  #   @user = User.find(params[:id])
  #   @users = @user.followers
  #   render 'show_follow'
  # end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  def demerituser(user,n)
    user.update_attribute :merits, user.merits - n
  end
  
end

app/views/users/_track.html.erb
<%= form_for(current_user.relationships.build(tracked_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :tracked_id %></div>
  <%= f.submit "Track", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_track_form.html.erb
<% unless current_user? %>
  <div id="track_form">
  <% if current_user.tracking?(@user) %>
    <%= render 'Stop Tracking' %>
  <% else %>
    <%= render 'Track' %>
  <% end %>
  </div>
<% end %>

app/views/users/_untrack.html.erb
<%= form_for(current_user.relationships.find_by_tracked_id(@user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Stop tracking", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<div class="user" id="<%= dom_id(user) %>">
	<% if user.admin? %>
	Admin image
	<% end %>

	<% if user.avatar.present? %>

		<%=link_to (image_tag user.avatar, :class => "user_image"), user_url(user.id) %>

	<% elsif user.pic_url.present? %>

		<%=link_to (image_tag user.pic_url, :class => "user_image"), user_url(user.id) %><br />

	<% else %>

		<%=link_to (image_tag "no-image.png" , :class => "user_image"), user_url(user.id) %><br />

	<% end %>
	
	PM(telephone icon)

	<%= link_to user.name, user_path(user.id) %><br/>
	<%= user.rank %><br />
	
	<div class="user_merits">
	<%=link_to user.merits, "", :class => '#{dom_id(user)}_merits' %>
	</div>

</div>

app/views/users/_user_nav.html.erb
<ul class="breadcrumb">
	
	<% if user == current_user %>

	  <li>
			<%=link_to "My Profile", user_url(user.id), :class => "divider"%>/
	  </li>
	  <li>
			<%=link_to "My Activity", activity_user_path(user.id), :class => "divider"%>/
	  </li>
	  <li>
			<%=link_to "My Documents", documents_user_path(user.id), :class => "divider"%>/
	  </li>
		<% else %>
	
	  <li>
			<%=link_to "#{user.name}'s public profile", user_url(user.id), :class => "divider"%>/
	  </li>
	  <li>
			<%=link_to "#{user.name}'s activity", activity_user_path(user.id), :class => "divider"%>/
	  </li>

	<% end %>

</ul>

app/views/users/activity.html.erb
<h2><%= @user.name %> has created <%= @user.convos.count %> conversations </h2>
	<%= render @user.convos %> 


<h2><%= @user.name %> has made <%= @user.posts.count %> posts</h2>
	<%#= render @user.posts %> 

app/views/users/avatar.html.erb
Upload your picture:

<%= form_for @user, :html => {:multipart => true} do |f| %>
  <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
	<% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.file_field :avatar %>
  </p>
  <p>
    <%= f.label :remote_avatar_url, "or image URL" %><br />
    <%= f.text_field :remote_avatar_url %>
  </p>

	<p>
		<label>
		<%= f.check_box :remove_avatar%>
		Remove picture
		</label>
  <p><%= f.submit %></p>
<% end %>

app/views/users/demerit.js.erb
$("#<%= dom_id(@user) %>_merits").html("<%= @user.merits %>");

app/views/users/documents.html.erb
Documents belonging to <%= @user.name %>

<%= @docs.each do |doc| %>
<%= @doc.name %>
<% end %>

<%= @convos.each do |convo| %>
	<%= convo.docs.each do |doc| %>
		<%=link_to doc.name %>
	<% end %>
<% end %>

<%= @posts.each do |post| %>
	<%= post.docs.each do |doc| %>
		<%=link_to doc.name %>
	<% end %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<!-- <%#= link_to "Upload avatar", user_avatar_url(:user_id => current_user.id)%><br>

<%# @users.each do |user|%>
	<%#=image_tag user.avatar%>
	<%# end %>
	
	<%#= if user_signed_in? %>
		<section>
       <%#= render 'shared/stats' %>
     </section>

<%#= render 'track_form' if signed_in? %>

<%# end %> -->

app/views/users/show.html.erb
<%= render 'user_nav', :user => @user %>

<% if @user.avatar.present? %>
	<%= image_tag @user.avatar, :class => "user_image" %>
<% elsif @user.pic_url.present? %>
	<%= image_tag @user.pic_url, :class => "user_image" %><br />
<% else %>
	<%= image_tag "no-image.png" , :class => "user_image" %><br />
<% end %>

<% if current_user == @user %>
<%= link_to "Upload picture", avatar_user_url(current_user.id) %>
<%#= button_to "Remove avatar", :onclick => current_user.avatar.remove! %>
<% else %>

Send private message (telephone icon)

<% end %>


<h3> Summary </h3>
<% if current_user == @user%>
	You have:<br />
<% else %>
	<%= @user.name %> has:<br />
<% end %>
<ul>
	<li> started <%= @user.convos.count %> conversations and made <%= @user.posts.count%> posts.</li>
	<li> earned <%= @user.merits %> merits.</li>
			<em> <%= link_to "Earn more merits!" , '#' %> </em>
	<li> logged in <%= @user.sign_in_count %> times</li>	
</ul>


<% if current_user == @user%>
	You are interested in:<br />
<% else %>
	<%= @user.name %> is interested in:<br />
<% end %>

<h3> <%= link_to "user.exams.count", "#" %> exams</h3>

<h3> Your Friends </h3>

You are <%= link_to "following", "#" %> users <br />
You are being <%= link_to "followed by", "#" %> users

<h3> Your Groups</h3>


Colleges and exams (private)
<% if current_user == @user%>
Private area (other users cannot see this) -- dropdown using jscipt?
<!-- Figure out how to checkbox for making this public; jscript for if checked, hide -->
You are interested in <%link_to "@user.colleges", "#"%> colleges
	
<% end %>

app/views/users/show_track.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %><br/></span>
      <span><b>Posts:</b> <%= @user.posts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/upmerit.erb
$("#<%= dom_id(@user) %>_merits").html("<%= @user.merits %>");