config/routes.rb
ApApp1::Application.routes.draw do
 
  root to: 'convos#index'

  resources :convos, :shallow => true do
    resources :docs
    resources :posts do
      resources :docs
    end
  end
    
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions=>'sessions'}
  resources :users, :only => [:show, :index, :update] do
    member do
      get :activity, :documents, :avatar#, :tracked, :trackers, 
    end
  end
  
  resources :subjects
  resources :topics
  resources :exams
  resources :colleges

  put 'upmerit_convo', to: 'convos#upmerit'
  put 'demerit_convo', to: 'convos#demerit'
  put 'upmerit_post', to: 'posts#upmerit'
  put 'demerit_post', to: 'posts#demerit'
 
  get "pages/home"
  get "pages/help"
  get "pages/about"
  get "pages/rules"

  

    
    

end

app/views/shared/_docs.html.erb
<section class= "docs">
	Attached Documents:
	<% item.docs.each do|doc|%>
	<!-- If doc is an image, return thumbnail (not full) version... -->
		<%=link_to (image_tag doc.attachment_url, :class => 'doc_image'), doc.attachment_url %>
		<%= link_to doc.name, doc.attachment_url, :class =>'doc_name' %><br />
		<span class="description"> 
		<%= doc.description %>
		</span>
		<% if signed_in? %>
				<% if current_user == doc.user || current_user.admin? %>
				<%=link_to "Edit", edit_doc_url(doc.id) %> | <%=link_to "Delete", doc_url(doc.id), method: :delete , :class => 'btn btn-danger'%>
				<% end %>
		<% end %>
		<hr>
				
	<% end%>
	
	  <% if signed_in? %>
				<% if current_user == item.user || current_user.admin %>
					<%= link_to "Upload", new_convo_doc_url(item.id), :class => 'btn btn-primary' %>
					<% end %>
		<% end %>

</section>

app/views/shared/_merits.html.erb
<!-- Add alternate image to create animation -->
	<span id="<%= dom_id(item) %>_upmerit">
		<%= link_to (image_tag "upmerit.png", :size => '20x20', :class => "upmerit"), "/upmerit_#{item.class.to_s.downcase}?id=#{item.id}", method: :put, remote: true %>
	</span>
	<span id = "<%= dom_id(item) %>_demerit">
		<%= link_to (image_tag "demerit.png", :size => '20x20', :class => "demerit"), "/demerit_#{item.class.to_s.downcase}?id=#{item.id}", method: :put, remote: true %>
	</span>
	<div id="<%= dom_id(item) %>_merits">
		<%= item.merits %>
	</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= tracked_user_path(@user) %>">
    <strong >
      <%= @user.tracked_users.count %>
    </strong>
    following
  </a>
  <a href="<%= trackers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.trackers.count %>
    </strong>
    followers
  </a>
</div>