config/routes.rb
ApApp1::Application.routes.draw do
 
  root to: 'convos#index'

  resources :convos, :shallow => true do
    resources :docs
    resources :posts do
      resources :docs
    end
  end
    
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions=>'sessions'}
  resources :users, :only => [:show, :index, :update] do
    member do
      get :activity, :documents, :avatar#, :tracked, :trackers, 
    end
  end
  
  resources :subjects
  resources :topics
  resources :exams
  resources :colleges

  put 'upmerit_convo', to: 'convos#upmerit'
  put 'demerit_convo', to: 'convos#demerit'
  put 'upmerit_post', to: 'posts#upmerit'
  put 'demerit_post', to: 'posts#demerit'
 
  get "pages/home"
  get "pages/help"
  get "pages/about"
  get "pages/rules"

  

    
    

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :convo_id, :merits, :skill, :title, :user_id, :parent_id, :convo
  
  has_ancestry
  belongs_to :convo
  belongs_to :user
  has_many :docs, :as => :docable
    
  validates :title, presence:true, length: { minimum: 8}
  validates :content, presence:true, length: { minimum: 15}
  
end
# == Schema Information
#
# Table name: posts
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  content    :text
#  user_id    :integer
#  convo_id   :integer
#  merits     :integer         default(0)
#  skill      :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  ancestry   :string(255)
#  file       :string(255)
#

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  # GET /posts
  # GET /posts.json
  #before_filter :require_user, :only => [:create, edit]
  #before_filter :require_admin, :only => [:destroy]
  def index
    @convo = Convo.find(params[:convo_id])
    @posts = @convo.posts.page(params[:page]).per_page(5)
    @post = Post.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @convo = Convo.find_by_id(params[:convo_id])
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @convo = Convo.find(params[:convo_id])
    @post = @convo.posts.new(:parent_id => params[:parent_id]) #=> dummy for form creation purposes
    @parent = @convo.posts.find_by_id(params[:parent_id]) #=> dummy for append purposes
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
      format.js
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @convo = Convo.find(params[:convo_id])
    @post = @convo.posts.new(params[:post])
    @post.user_id = current_user.id
    @user = current_user
    upmerituser(current_user, 5)
    @parent = @convo.posts.find_by_id(params[:parent_id])

    respond_to do |format|
      if @post.save
        format.html { redirect_to convo_posts_url, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render json: @post.merits }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to @post.convo }
      format.json { head :no_content }
    end
  end
  
  def upmerit
    @post = Post.find(params[:id])
    if demerituser(current_user,1)
      @post.update_attribute :merits, @post.merits + 1
    end
    respond_to do |f|
      f.js
    end
  end
  
  def demerit
    @post = Post.find(params[:id])
    if demerituser(current_user,2)
      @post.update_attribute :merits, @post.merits - 1
    end
    respond_to do |f|
      f.js
    end
  end
  
  def file
    @post = Post.find(params[:user_id])
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def nested_posts(posts)
    posts.map do|post, sub_posts|
      render(post) + content_tag(:div, nested_posts(sub_posts), :class => "nested_posts")
    end.join.html_safe
  end
  
end

app/views/posts/_form.html.erb
<%= form_for @post, url:convo_posts_path(@convo) do |f| %>

	<% if @post.errors.any? %>
	 <div id="error_explanation">
	   <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

	   <ul>
	   <% @post.errors.full_messages.each do |msg| %>
	     <li><%= msg %></li>
	   <% end %>
	   </ul>
	 </div>
	<% end %>
	
	<% if user_signed_in? 
		user_id = current_user.id %>
	<%=f.hidden_field :user_id %>
	<% end %>
	
	<%=f.hidden_field :parent_id %>
	
	<%= f.text_field :title, placeholder: "Title" %>
	
	<br /><%= f.text_area :content, :size =>'10x10',placeholder: "Merits for your thoughts?" %>
	
<br /><%= f.submit "Post" , :remote => true%>
	
<% end %>

app/views/posts/_new.html.erb
<%= render 'form' %>

app/views/posts/_post.html.erb
<article class ="post linearBg2" id = "<%= dom_id(post) %>">	
		
		<%= render 'users/user', :user => post.user %>


			<header class = "title">
				<h2>
					<%=link_to post.title, post %>
				</h2>
			</header>
		
			<%= render 'shared/merits', :item => post %>
			<%= render 'shared/docs', :item => post %>
			
			<div class="post_text">
			 <%= raw post.content %>
			</div>
			
					<%if signed_in? %>
						<% if current_user.admin?%>
							<%= link_to "Edit", edit_post_url(post.id)%> | <%= link_to "Delete", post_url(post.id), method: :delete %>
						<% elsif current_user == post.user && post.created_at < 1.day.ago %>
							<%= link_to "Edit", edit_post_url(post.id)%> | <%= link_to "Delete", post_url(post.id), method: :delete %>
							<% else %>
							Locked for editing after 1 day
							<% end %>
						<% end%>

			|<%= link_to "Reply", new_convo_post_path(:convo_id => post.convo.id,:class => 'btn btn-primary', :parent_id => post.id), :remote => true %>			
			<!-- Admin will see delete button here -->

</article>

app/views/posts/create.js.erb
<% if @parent.present? %>
$('#<%= dom_id(@parent)%>').append('<%= escape_javascript(render "post" ,:post => @post) %>');
$("#<%= dom_id(@user) %>_merits").html("<%= @user.merits %>");
<% else %>
$("#posts").append('<%= escape_javascript(render "post" ,:post => @post) %>');
<% end %>

//Clear form fieldk; change this to clear tiny mce instead ...
$('#post_content').val(null);
$('#post_title').val(null);

app/views/posts/demerit.js.erb
$("#<%= dom_id(@post) %>_merits").html("<%= @post.merits %>");

app/views/posts/edit.html.erb
<h3> Edit this post </h3>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Cancel', posts_path %>

app/views/posts/edit.js.erb
 $('#new_input').hide();
 $('#<%= dom_id(@note)%>').html("<%= j(render 'form') %>")

app/views/posts/index.html.erb
<section id="convos">
<%= render 'convos/convo', :convo => @convo %>
</section>

<section id="posts">
	<%= nested_posts @posts.arrange(:order => :created_at) %> 

</section>

<div class="post_form">
<%= render 'new' %>
</div>

<%= will_paginate %>

app/views/posts/new.js.erb
$('#new_input').hide();
$('#<%= dom_id(@parent)%>').append("<div class='post_form'><%= j(render 'form')%></div>");
// Need to find a way to pass the parent's id

app/views/posts/show.html.erb
Comment posted by <%= @post.user_id %> at <%= @post.created_at.localtime.strftime("%m/%d/%y %H:%M") %>

<%= nested_posts @post.subtree.arrange(:order => :created_at ) %>

<%= link_to 'Back to posts', convo_posts_url(@post.convo.id) %>

app/views/posts/upmerit.js.erb
$("#<%= dom_id(@post) %>_merits").html("<%= @post.merits %>");