config/routes.rb
ApApp1::Application.routes.draw do
 
  root to: 'convos#index'

  resources :convos, :shallow => true do
    resources :docs
    resources :posts do
      resources :docs
    end
  end
    
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :sessions=>'sessions'}
  resources :users, :only => [:show, :index, :update] do
    member do
      get :activity, :documents, :avatar#, :tracked, :trackers, 
    end
  end
  
  resources :subjects
  resources :topics
  resources :exams
  resources :colleges

  put 'upmerit_convo', to: 'convos#upmerit'
  put 'demerit_convo', to: 'convos#demerit'
  put 'upmerit_post', to: 'posts#upmerit'
  put 'demerit_post', to: 'posts#demerit'
 
  get "pages/home"
  get "pages/help"
  get "pages/about"
  get "pages/rules"

  

    
    

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">WhizAP</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   pages_about_url %></li>
			<li><%= link_to "Rules", pages_rules_url %></li>
			<li><%= link_to "Contact",  '#' %></li>
      <li><%= link_to "Help", pages_help_url %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_forum_nav.html.erb
 <div class="row">
		<div class="tabs">
	      <ul>			
	        <%= nav_link "All", convos_url %>
					<%= nav_link 'Calculus', convos_url(:subject_name => "Calculus")%>
	        <%= nav_link 'Economics', convos_url(:subject_name =>"Economics") %>
	        <%= nav_link 'History', convos_url(:subject_name => "History") %>
	      </ul>
	    </div>
	</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "WhizAP", root_path, id: "logo" %>

      <nav>
				<form class="navbar-search" action="/convos" method="get">
					<input type="text" name="query" class="span2" placeholder="Search WhizAP">
					</form>
        <ul class="nav pull-right">
					<li><%#= link_to "Lessons", "#" %></li>
					<% if user_signed_in? %>	
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">
							<%= current_user.name %><br/><%= current_user.rank%><br/>
							<span class='<%=dom_id(current_user)%>_merits'> <%= current_user.merits %> merits</span>
							<b class="caret"> </b>
						</a>
							<ul class="dropdown-menu">
								<li><a href="#"><i class="icon-user"></i>Profile</a></li>
								<li><a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow"><i class="icon-remove"></i>Sign Out</a></li>
							</ul>
						</li>
						
						<% if current_user.avatar.present? %>
							<%= link_to (image_tag current_user.avatar, :class => "user_image"), user_url(current_user.id) %>
						<% elsif current_user.pic_url.present? %>
							<%= link_to (image_tag current_user.pic_url, :class => "user_image"), user_url(current_user.id) %><br />
						<% else %>
							<%= link_to (image_tag "no-image.png" , :class => "user_image"), user_url(current_user.id) %><br />
						<% end %>
						
						<% else %>
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">
								Sign In
								<b class="caret"> </b>
							</a>
								<ul class="dropdown-menu">
								<li><%= link_to "Sign In - Facebook", user_omniauth_authorize_path(:facebook) %></li>
								<li><%= link_to "Sign In - Email", new_user_session_path %></li>
								<li><%= link_to "Register", new_user_registration_path %></li>
								</ul>
							</li>
						<% end %>
  
        </ul>
      </nav>
    </div>
  </div>
</header><br/>

<%if signed_in? %>
	<% if current_user.admin %>
	<header class="navbar navbar fixed-top">
			Admin bar:
			<%= link_to "Subjects", subjects_url %>|
			<%= link_to "Topics", topics_url %>|
			<%= link_to "Exams", exams_url %>|
			<%= link_to "Users", users_url %>|
			<%= link_to "Lessons", '#' %>
		</header>
	<% end %>
<% end %>
	
<% flash.each do |name,msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

app/views/layouts/_sidebar.html.erb
<aside class= "sidebar">
	<h4> Most popular conversations </h4>
	<% popular.each  do |convo| %><br />
	<%= link_to convo.title, convo_url(convo.id) %> | merits: <%= convo.merits %> <hr>
	<% end  %>
	</aside>

app/views/layouts/_subject_nav.html.erb
 <div class="row">
		<div class="tabs">
	      <ul>			
	        <%= nav_link "All", convos_url %>
					<%= nav_link 'Math', convos_url(:subject_name => "Mathematics")%>
	        <%= nav_link 'Social Science', convos_url(:subject_name =>"Social Science") %>
	        <%= nav_link 'Natural Science', convos_url(:subject_name => "Natural Science") %>
	        <%= nav_link 'Languages / Literature', convos_url(:subject_name => "Languages/Lit") %>
	        <%= nav_link 'Humanities', convos_url(:subject_name => "Art/Humanities") %>
	<% if user_signed_in? %>
	<div class="mywhiz">
	<%= nav_link 'My WhizAP',user_url(current_user.id) %>
	</div>
  <% end %>
	
	      </ul>
	    </div>
	</div>

app/views/layouts/_topic_nav.html.erb
<br/>
<ul class="breadcrumb topics">
	<% subject.topics.each do |topic|%>
		<li>
			<%=link_to topic.name, convos_url(:topic_id => topic.id), :class => is_active?(topic.id) %><span class="divider">/</span>
	  </li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	  <![endif]-->
	</head>
	<body>
		<div class="container">	
				<%= render '/layouts/header'%>
				
				<h1><%= page_heading(yield(:header))%></h1>
						
							<div class="span12 content">
									<%= render 'layouts/subject_nav' unless no_forum_nav? %>
									<div class="span9">
									<%= yield %>
									</div>	
									<div class="span2">
										<%= yield :sidebar %>
									</div>		
							</div>

					 <%= render '/layouts/footer'%>
						<br /><br /><br />
					<p>AP and Advanced Placement are registered trademarks of the College Board, which is not involved in, and does not endorse WhizAP.</p><br /><br />	
				
			</div>


	</body>
</html>